# Input
IN_COLOR_WIDTH = 1 # px

# Output
OUT_COLOR_PER_COLUMN = 8
OUT_COLOR_WIDTH = 64 # px
OUT_COLOR_HEIGHT = OUT_COLOR_WIDTH #px
OUT_GRADIENT_OFFSET_Y = OUT_COLOR_HEIGHT // 2
OUT_FILE_NAME = "./output.png"